trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseYUNIQLCLI@0
  inputs:
    version: 'latest'

- task: RunYUNIQLCLI@0
  inputs:
    version: 'latest'
    connectionString: '$(AzSqlDemoDatabase)'
    workspacePath: '$(Build.SourcesDirectory)\samples\helloyuniql-db'
    targetPlatform: 'SqlServer'
    additionalArguments: '--debug'